NG_DOCS={
  "sections": {
    "module": "Module Documentation",
    "rest-api": "API Documentation"
  },
  "pages": [
    {
      "section": "module",
      "id": "xos.helpers",
      "shortName": "xos.helpers",
      "type": "overview",
      "moduleName": "xos.helpers",
      "shortDescription": "this is the module that group all the helpers service and components for XOS",
      "keywords": "components group helpers module overview service xos"
    },
    {
      "section": "module",
      "id": "xos.helpers.LabelFormatter",
      "shortName": "xos.helpers.LabelFormatter",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "This factory define a set of helper function to format label started from an object property",
      "keywords": "define factory format function helper helpers label labelformatter module object property service set started xos"
    },
    {
      "section": "module",
      "id": "xos.helpers.NoHyperlinks",
      "shortName": "xos.helpers.NoHyperlinks",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "This factory is automatically loaded trough xos.helpers and will add an $http interceptor that will add ?no_hyperlinks=1 to your api request, that is required by django",
      "keywords": "$http add api automatically django factory helpers interceptor loaded module nohyperlinks request required service trough xos"
    },
    {
      "section": "module",
      "id": "xos.helpers.SetCSRFToken",
      "shortName": "xos.helpers.SetCSRFToken",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "This factory is automatically loaded trough xos.helpers and will add an $http interceptor that will the CSRF-Token to your request headers",
      "keywords": "$http add automatically csrf-token factory headers helpers interceptor loaded module request service setcsrftoken trough xos"
    },
    {
      "section": "module",
      "id": "xos.uiComponents",
      "shortName": "xos.uiComponents",
      "type": "overview",
      "moduleName": "xos.uiComponents",
      "shortDescription": "A collection of UI components useful for Dashboard development.",
      "keywords": "collection components currently dashboard development directive module overview ui uicomponents xos"
    },
    {
      "section": "module",
      "id": "xos.uiComponents.directive:xosAlert",
      "shortName": "xosAlert",
      "type": "directive",
      "moduleName": "xos.uiComponents",
      "shortDescription": "The xos-alert directive",
      "keywords": "alert angular animations autohide automatically binding btn btn-block btn-default button class close closebtn col-sm-4 col-sm-8 config config1 config2 config3 config4 config5 configuration controller danger default directive displayed false function hide html info js message module ng-click ng-controller ng-show nganimate object row sample samplealert1 samplealert2 samplectrl samplectrl1 script success true type uicomponents vm warning xos xos-alert"
    },
    {
      "section": "module",
      "id": "xos.uiComponents.directive:xosForm",
      "shortName": "xosForm",
      "type": "directive",
      "moduleName": "xos.uiComponents",
      "shortDescription": "The xos-form directive.",
      "keywords": "$window actions active age angular autogenerate autogenerated birthdate boolean bootstraps buttons callback cb class components concatenated config configuration configured console controller create created custom define defined deleted directive doe email exclude factory field field_name fields first_name form formname function glyphicon html icon jhon js label last_login last_name log max maxlength min minlength model module ng-controller ng-model number object options password provide receive refers required return samplectrl samplectrl1 sampleform sampleform1 save script skipped string success surname true type uicomponents updated usage validators values vm xos xos-form"
    },
    {
      "section": "module",
      "id": "xos.uiComponents.directive:xosPagination",
      "shortName": "xosPagination",
      "type": "directive",
      "moduleName": "xos.uiComponents",
      "shortDescription": "The xos-table directive",
      "keywords": "angular callback change collection console controller directive elements function html js log module ng-controller number page-size pagesize samplectrl1 samplepagination script total total-elements totalelements triggered uicomponents vm xos xos-table"
    },
    {
      "section": "module",
      "id": "xos.uiComponents.directive:xosSmartPie",
      "shortName": "xosSmartPie",
      "type": "directive",
      "moduleName": "xos.uiComponents",
      "shortDescription": "The xos-table directive",
      "keywords": "$httpbackend $resource $timeout $window aaa active angular angularjs api aria array assign backend backendpoll banned category classes component composed config configlocal configuration controller danaerys data datas directive directly displaying dragon factory fetching field fieldname first_name format function group groupby headers html jon js label labelformatter labels lannister last_name local map mock module my-custom-class ng-controller ngdoc ngmocke2e ngresource north order org params poll polling random resource respond return round samplectrl samplectrllocal sampleresource samplesmartpielocal samplesmartpiepoll samplesmartpieresource script service snow stark targaryen triggered tyrion uicomponents url users vm whenget xos xos-table"
    },
    {
      "section": "module",
      "id": "xos.uiComponents.directive:xosSmartTable",
      "shortName": "xosSmartTable",
      "type": "directive",
      "moduleName": "xos.uiComponents",
      "shortDescription": "The xos-table directive",
      "keywords": "$httpbackend $resource $window angular angularjs array component composed config configuration controller count data datas directive documentation doe example factory fields fromjson function headers hiddenfields html jhon js match module ng-controller ngmocke2e ngresource org params paramsurl parseint printed purpose push regexp remove resource respond return samplectrl sampleresource samplesmarttable script service shouldn start surname uicomponents undefined url users vm whendelete whenget whenpost xos xos-table xosform xostable"
    },
    {
      "section": "module",
      "id": "xos.uiComponents.directive:xosTable",
      "shortName": "xosTable",
      "type": "directive",
      "moduleName": "xos.uiComponents",
      "shortDescription": "The xos-table directive",
      "keywords": "$window action actions add angular animations array arrows basic boolean bootstraps c_tag cache callback cb cdn cdnenabled clarkson classes color column columns component config configuration console controller custom data default defined delete details directive disabled doe downlink downlink_speed enabled factory false features feeded fereydoun field filter filtering formatter full fulltext function gili glyphicon google html https human icon icons iptv item john js label lastname link log lucky model module ng-controller nganimate object order ordering pagesize pagination prop property read readable receive red refers remove rendered return s_tag samplectrl samplectrl1 samplectrl2 samplectrl3 sampletable1 sampletable2 sampletable3 sampletable4 sampletable5 script services spalding speed status table table-bordered table-condensed table-striped tate title true type uicomponents uplink uplink_speed usage username uverse val vm xos xos-table"
    },
    {
      "section": "module",
      "id": "xos.uiComponents.directive:xosValidation",
      "shortName": "xosValidation",
      "type": "directive",
      "moduleName": "xos.uiComponents",
      "shortDescription": "The xos-validation directive",
      "keywords": "angular btn btn-default btn-success class col-xs-12 col-xs-2 controller directive email error errors false function html js length max maxlength min minlength module ng-class ng-click ng-controller object required row samplectrl samplevalidation script type uicomponents vm xos xos-validation"
    },
    {
      "section": "rest-api",
      "id": "xos.helpers.Deployments",
      "shortName": "xos.helpers.Deployments",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "Angular resource to fetch /api/core/deployments/:id/",
      "keywords": "angular deployments fetch helpers resource rest-api service xos"
    },
    {
      "section": "rest-api",
      "id": "xos.helpers.Example-Services-Collection",
      "shortName": "xos.helpers.Example-Services-Collection",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "Angular resource to fetch /api/service/exampleservice/",
      "keywords": "angular example-services-collection fetch helpers resource rest-api service xos"
    },
    {
      "section": "rest-api",
      "id": "xos.helpers.Flavors",
      "shortName": "xos.helpers.Flavors",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "Angular resource to fetch /api/core/flavors/:id/",
      "keywords": "angular fetch flavors helpers resource rest-api service xos"
    },
    {
      "section": "rest-api",
      "id": "xos.helpers.Instances",
      "shortName": "xos.helpers.Instances",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "Angular resource to fetch /api/core/instances/:id/",
      "keywords": "angular fetch helpers instances resource rest-api service xos"
    },
    {
      "section": "rest-api",
      "id": "xos.helpers.Login",
      "shortName": "xos.helpers.Login",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "Angular resource to fetch /api/utility/login/",
      "keywords": "angular fetch helpers login resource rest-api service xos"
    },
    {
      "section": "rest-api",
      "id": "xos.helpers.Logout",
      "shortName": "xos.helpers.Logout",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "Angular resource to fetch /api/utility/logout/",
      "keywords": "angular fetch helpers logout resource rest-api service xos"
    },
    {
      "section": "rest-api",
      "id": "xos.helpers.Nodes",
      "shortName": "xos.helpers.Nodes",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "Angular resource to fetch /api/core/nodes/:id/",
      "keywords": "angular fetch helpers nodes resource rest-api service xos"
    },
    {
      "section": "rest-api",
      "id": "xos.helpers.ONOS-App-Collection",
      "shortName": "xos.helpers.ONOS-App-Collection",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "Angular resource to fetch /api/tenant/onos/app/",
      "keywords": "angular fetch helpers onos-app-collection resource rest-api service xos"
    },
    {
      "section": "rest-api",
      "id": "xos.helpers.ONOS-Services-Collection",
      "shortName": "xos.helpers.ONOS-Services-Collection",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "Angular resource to fetch /api/service/onos/",
      "keywords": "angular fetch helpers onos-services-collection resource rest-api service xos"
    },
    {
      "section": "rest-api",
      "id": "xos.helpers.Sites",
      "shortName": "xos.helpers.Sites",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "Angular resource to fetch /api/core/sites/:id/",
      "keywords": "angular fetch helpers resource rest-api service sites xos"
    },
    {
      "section": "rest-api",
      "id": "xos.helpers.Slices",
      "shortName": "xos.helpers.Slices",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "Angular resource to fetch /api/core/slices/:id/",
      "keywords": "angular fetch helpers resource rest-api service slices xos"
    },
    {
      "section": "rest-api",
      "id": "xos.helpers.Subscribers",
      "shortName": "xos.helpers.Subscribers",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "Angular resource to fetch Subscribers",
      "keywords": "angular fetch helpers method read-subscriber-cdn read-subscriber-downlink_speed read-subscriber-status read-subscriber-uplink_speed read-subscriber-uverse resource rest-api service subscribers update-subscriber-cdn update-subscriber-downlink_speed update-subscriber-status update-subscriber-uplink_speed update-subscriber-uverse view-a-subscriber-features-detail xos"
    },
    {
      "section": "rest-api",
      "id": "xos.helpers.Truckroll-Collection",
      "shortName": "xos.helpers.Truckroll-Collection",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "Angular resource to fetch /api/tenant/truckroll/:truckroll_id/",
      "keywords": "angular fetch helpers resource rest-api service truckroll-collection xos"
    },
    {
      "section": "rest-api",
      "id": "xos.helpers.Users",
      "shortName": "xos.helpers.Users",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "Angular resource to fetch /api/core/users/:id/",
      "keywords": "angular fetch helpers resource rest-api service users xos"
    },
    {
      "section": "rest-api",
      "id": "xos.helpers.vOLT-Collection",
      "shortName": "xos.helpers.vOLT-Collection",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "Angular resource to fetch /api/tenant/cord/volt/:volt_id/",
      "keywords": "angular fetch helpers resource rest-api service volt-collection xos"
    },
    {
      "section": "rest-api",
      "id": "xos.helpers.vSG-Collection",
      "shortName": "xos.helpers.vSG-Collection",
      "type": "service",
      "moduleName": "xos.helpers",
      "shortDescription": "Angular resource to fetch /api/service/vsg/",
      "keywords": "angular fetch helpers resource rest-api service vsg-collection xos"
    }
  ],
  "apis": {
    "module": true,
    "rest-api": true
  },
  "__file": "_FAKE_DEST_/js/docs-setup.js",
  "__options": {
    "startPage": "/module",
    "scripts": [
      "js/angular.min.js",
      "js/angular-animate.min.js",
      "js/marked.js",
      "https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7/angular-mocks.js",
      "../xos/core/xoslib/static/js/vendor/ngXosVendor.js",
      "../xos/core/xoslib/static/js/vendor/ngXosHelpers.js"
    ],
    "styles": [
      "../xos/core/static/xosNgLib.css",
      "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.css"
    ],
    "title": "XOS Helpers documentation",
    "html5Mode": false,
    "editExample": true,
    "navTemplate": false,
    "navContent": "",
    "navTemplateData": {},
    "loadDefaults": {
      "angular": true,
      "angularAnimate": true,
      "marked": true
    }
  },
  "html5Mode": false,
  "editExample": true,
  "startPage": "/module",
  "scripts": [
    "js/angular.min.js",
    "js/angular-animate.min.js",
    "js/marked.js",
    "https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.7/angular-mocks.js",
    "../xos/core/xoslib/static/js/vendor/ngXosVendor.js",
    "../xos/core/xoslib/static/js/vendor/ngXosHelpers.js"
  ]
};